# Translations template for heat.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the heat project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Heat\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-08-20 06:01+0000\n"
"PO-Revision-Date: 2014-08-07 07:52+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Spanish (http://www.transifex.com/projects/p/heat/language/"
"es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: heat/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Se está descartando excepción original: %s"

#: heat/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "La excepción inesperada ha ocurrido %d vez(veces)... reintentando."

#: heat/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "No se ha podido liberar el bloqueo adquirido `%s`"

#: heat/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "en llamada en bucle de duración fija"

#: heat/openstack/common/loopingcall.py:131
msgid "in dynamic looping call"
msgstr "en llamada en bucle dinámica"

#: heat/openstack/common/policy.py:507
#, python-format
msgid "Failed to understand rule %s"
msgstr "Ha ocurrido un error al interpretar la regla %s"

#: heat/openstack/common/policy.py:517
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No hay manejador para coincidencias de clase %s"

#: heat/openstack/common/policy.py:787
#, python-format
msgid "Failed to understand rule %r"
msgstr "Ha ocurrido un error al interpretar la regla %r"

#: heat/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Excepción durante limpieza de rpc."

#: heat/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Excepción no controlada"
